
#define DEFAULT_PORT 6423
#define DEFAULT_HOSTNAME "localhost"
#define MAX_FILE_PATH_LENGTH 100
#define MAX_USERNAME 50
#define MAX_PASSWORD 50
#define MAX_LINE_LENGTH 200
#define MAX_HOSTNAME_LENGTH 200

#define STATE_SUCCESS 0
#define STATE_ERROR 1
#define STATE_SHUTDOWN 2
